def acronym_word(text):
    text = text.replace('bm','bộ môn')
    text = text.replace('dh','đại học')
    text = text.replace('đh','đại học')
    text = text.replace('gdqp','giáo dục quốc phòng')
    text = text.replace('gdtc','giáo dục thể chất')
    text = text.replace('khoa dd','khoa điều dưỡng')
    text = text.replace('khoa đd','khoa điều dưỡng')
    text = text.replace('khoa khcb','khoa khoa học cơ bản')
    text = text.replace('khoa vlls','khoa vật lý lý sinh')
    text = text.replace('khoa yhct','khoa y học cổ truyền')
    text = text.replace('khoa ytcc','khoa y tế công cộng')
    text = text.replace('khoa ytcd','khoa y tế công cộng')
    text = text.replace('khoa ytcđ','khoa y tế cộng đồng')
    text = text.replace('phòng cb','phòng tổ chức cán bộ')
    text = text.replace('phòng dbcl','phòng đảm bảo chất lượng')
    text = text.replace('phòng đbcl','phòng đảm bảo chất lượng')
    text = text.replace('phòng dt','phòng đào tạo')
    text = text.replace('phòng đt','phòng đào tạo')
    text = text.replace('phòng dtdh','phòng đào tạo')
    text = text.replace('phòng đtđh','phòng đào tạo')
    text = text.replace('phòng hc','phòng hành chính')
    text = text.replace('phòng hcth','phòng hành chính')
    text = text.replace('phòng kt','phòng khảo thí')
    text = text.replace('phòng nckh qhdn','phòng nghiên cứu khoa học quan hệ đối ngoại')
    text = text.replace('phòng nckhqhdn','phòng nghiên cứu khoa học quan hệ đối ngoại')
    text = text.replace('phòng qlda','phòng quản lý dự án')
    text = text.replace('phòng qttb','phòng quản trị thiết bị')
    text = text.replace('phòng tccb','phòng tổ chức cán bộ')
    text = text.replace('phòng ttpc','phòng thanh tra')

    return text
